id: P4232A459
initial_creation_type: input
source_metadata:
  title: Tsongkhapa Lobzang Drakpa Series
  language: en
  description: 'Texts by and about the great master Tsongkhapa Lobzang Drakpa (tsong
    kha pa blo bzang grags pa) (1357–1419), founder of the Gelug school:'
  volume:
    06adcba37f2a4cf480de7cc1cc1b3569:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    0025013b42304f689a2d5ba70422fada:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Guru Yoga
    a6585378b9fc473d92efc83e64829dae:
      title: Three Principal Aspects of the Path
      parent: Mind Training
    178c074815b54a54b21fc4faea01cd4e:
      title: Praise to Mañjughoṣa
      parent: Praise
    f7c7ed50736b41879a0fdd79d0db5e26:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Praise
    3b32d92488e649ddb2b7bd095ac86048:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    8ad365f824be4e9486c0d4e75d166de1:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
    36f47f25307448ccb653e500d4e6890e:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T01:55:51.972485'
last_modified_at: '2022-03-01T01:55:51.972491'
